/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appBanco;

import java.util.List;
import javax.swing.JOptionPane;
import ws.ServicoConta;
import ws.ServicoContaService;

/**
 *
 * @author jrcio
 */
public class ConsumidoraConta extends javax.swing.JFrame {

    /**
     * Creates new form ConsumidoraConta
     */
    public ConsumidoraConta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botaoConsultar = new javax.swing.JButton();
        txtIdConta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelSaldo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        botaoCadastrar = new javax.swing.JButton();
        botaoSaque = new javax.swing.JButton();
        botaoDeposito = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número da conta:");

        botaoConsultar.setText("Consultar");
        botaoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarActionPerformed(evt);
            }
        });

        txtIdConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdContaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel3.setText("Saldo:");

        labelNome.setText("Digite o número da conta primeiro!!!");

        labelSaldo.setText("Digite o número da conta primeiro!!!");

        jLabel6.setText("Valor:");

        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        botaoSaque.setText("Saque");
        botaoSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSaqueActionPerformed(evt);
            }
        });

        botaoDeposito.setText("Depósito");
        botaoDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDepositoActionPerformed(evt);
            }
        });

        jLabel4.setText("Senha:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSaldo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNome)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(botaoCadastrar)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSenha)
                            .addComponent(txtIdConta))
                        .addGap(18, 18, 18)
                        .addComponent(botaoConsultar)
                        .addGap(24, 24, 24))))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(botaoSaque)
                .addGap(33, 33, 33)
                .addComponent(botaoDeposito)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIdConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(botaoConsultar)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelSaldo))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadastrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSaque)
                    .addComponent(botaoDeposito))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarActionPerformed
        // TODO add your handling code here:
        
        if(txtIdConta.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo IDConta é obrigatório", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(txtSenha.getText().equals("")){
        JOptionPane.showMessageDialog(null, "O campo Senha é obrigatório", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
        }
        
               try {
            ws.ServicoContaService servico = new ws.ServicoContaService();
            ws.ServicoConta webservice = servico.getServicoConta();

            List<String> resultado = (List<String>) webservice.consultarDadosConta(Integer.parseInt(txtIdConta.getText()), txtSenha.getText());

            //Se resultado não retornou vazio
            if (!resultado.get(0).equals("")) {
                //Exibe resultado da busca
                labelNome.setText(resultado.get(0));
                labelSaldo.setText(resultado.get(1));

                //Ativa a caixa de texto e botões para Saque e Depósito
                txtValor.setEnabled(true);
                botaoSaque.setEnabled(true);
                botaoDeposito.setEnabled(true);
            }  
            else {
                //Alerta se resultado não encontrado
                JOptionPane.showMessageDialog(null, "Conta não encontrada!");
            }
        } catch (Exception ex) {
            System.out.println("Erro: " + ex.getMessage());
        }


    }//GEN-LAST:event_botaoConsultarActionPerformed

    private void botaoSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSaqueActionPerformed
          if(txtIdConta.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo IDConta é obrigatório", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(txtSenha.getText().equals("")){
        JOptionPane.showMessageDialog(null, "O campo Senha é obrigatório", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        // TODO add your handling code here:
        try {
            ws.ServicoContaService servico = new ws.ServicoContaService();
            ws.ServicoConta webservice = servico.getServicoConta();
            
            if(Double.parseDouble(txtValor.getText()) > 0){
                webservice.saqueConta(Double.parseDouble(txtValor.getText()), Integer.parseInt(txtIdConta.getText()), txtSenha.getText());
                JOptionPane.showMessageDialog(null, "Saque realicado com sucesso!");
            }else {
                JOptionPane.showMessageDialog(null, "Impossivel depositar ou sacar valor negativo!");
            }
            this.botaoConsultarActionPerformed(evt);
        
        
        }catch (Exception erro) {
            System.out.println("Erro: " + erro.getMessage());
        }
        
    }//GEN-LAST:event_botaoSaqueActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        // TODO add your handling code here:
                
        //Chama o cadastro Form
            new Cadastro().setVisible(true);
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDepositoActionPerformed
        // TODO add your handling code here:
        
        if(txtIdConta.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo IDConta é obrigatório", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(txtSenha.getText().equals("")){
        JOptionPane.showMessageDialog(null, "O campo Senha é obrigatório", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        try {
            ws.ServicoContaService servico = new ServicoContaService();
            ws.ServicoConta webservice = servico.getServicoConta();

            if (Double.parseDouble(txtValor.getText()) > 0) {
                webservice.depositoConta(Double.parseDouble(txtValor.getText()), Integer.parseInt(txtIdConta.getText()), txtSenha.getText());
            } else {
                JOptionPane.showMessageDialog(null, "Impossivel depositar ou sacar valor negativo!");
            }
            this.botaoConsultarActionPerformed(evt);

        } catch (Exception erro) {
            System.out.println("Erro: " + erro.getMessage());
        }
    }//GEN-LAST:event_botaoDepositoActionPerformed

    private void txtIdContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdContaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsumidoraConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsumidoraConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsumidoraConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsumidoraConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsumidoraConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoConsultar;
    private javax.swing.JButton botaoDeposito;
    private javax.swing.JButton botaoSaque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JTextField txtIdConta;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
